services:
  - type: web
    name: kucovatoday
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/articles
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
